// Script: 'testuser.js' , generated by Gamedonia
var print_test_results = true;

var testmark = gamedonia.data.newEntity();

var d = new Date();
testmark.date = d.toString();
testmark.api = "users";

var query = "{}";
 
gamedonia.user.search( query, {
   success: function(res_search) {

               var res = res_search.get(0);
           response.success();
   },
   error: function(error) {

           printTest("SEARCH", false);
           log.error(error.message);
           response.error(error.message);
   }
});