// Script: 'test.js' , generated by Gamedonia
var result = {};


gamedonia.data.search("saga_trips","{}",{
   success:function(trips) {
       var trip_ids = [];
       result.trips={};
       
       trips.forEach(function(triprow) {
           trip_ids.push(triprow.trip_id);
           result.trips[triprow.trip_id]={
        		   trip_name:triprow.trip_name,
        		   cities:{}
           };
       });    
       var city_query = "{\"trip_id\":{ $in :["+trip_ids+"]}}";
       
       gamedonia.data.search("saga_cities",city_query,{
           success:function(cities) {
              
               var city_ids = [];
                cities.forEach(function(cityrow) {
                   city_ids.push(cityrow.city_id);
                   
                   var theTrip = result.trips[cityrow.trip_id];
                   theTrip.cities[cityrow.city_id] = {
                		   city_name:cityrow.city_name,
                		   reward_coins:cityrow.reward_coins,
                		   chapters:{}
                   };
               });
              
               var chapter_query = "{\"city_id\":{ $in :["+city_ids+"]}}";
               gamedonia.data.search("saga_chapters",chapter_query,{
                   success:function(chapters) {
                       chapters.forEach(function(chapterrow) {
                           var theCity = result.trips[chapterrow.trip_id].cities[chapterrow.city_id];
                           theCity.chapters[chapterrow.chapter_id] = {
                        		   chapter_name:chapterrow.chapter_name
                           };
                       });
                       response.success(result); 
                   },error:function(error) {
                       response.success(error.message);
                   }
               });
           },error:function(error) {
               response.success(error.message);
           }    
       });
   }, error:function(error) {
       response.success(error.message);
       
   }    
});