// Script: 'runbulk.js' , generated by Gamedonia

var operations = [];
out.println("aaaa")
operations.push(gamedonia.data.createUpdate("{}","{\"$inc\": { \"amount\": -2 }}"));

gamedonia.data.runBulkOperations("moviesdos", operations, {
   success: function(result) {      
       
       log.info("The bulk op was done fine.");
       out.println("The bulk op was done fine.");
       
   },
   error: function(error) {
       log.error(error.message);
       out.println("ERRRORRRRRR: " + error.message);
       response.error(error.message);
     }
});
