// Script: 'test.js' , generated by Gamedonia
var result = {};
out.println(JSON.stringify({patata:'hola'}));
function toEntityData(obj){
	var entity = gamedonia.data.newEntity();
	for(prop in obj){
		entity.put(prop,obj[prop]);
	}
	return entity;
}
gamedonia.data.search("apm","{}",{
	success:function(e){
		out.println("LENGTH: " + e.length);
		out.println("SIZE: " + e.size());
	}
});

gamedonia.data.search("saga_trips","{}",{
   success:function(trips) {
       var trip_ids = [];
       result.trips={};
       var theType = typeof(trips);
       var theType2 = typeof(trip_ids);
//       trips=[];
       out.println("FOREACH: "+trips.forEach);
       trips.forEach(function(triprow) {
           trip_ids.push(triprow.trip_id);
           var keys = Object.keys(triprow);

           keys.forEach(function(p){
        	   out.println("PROPERTY2: " + p);
           });
           result.trips[triprow.trip_id]=triprow;
       });    
       var city_query = "{\"trip_id\":{ $in :["+trip_ids+"]}}";
       gamedonia.data.search("saga_cities",city_query,{
           success:function(cities) {
              
               var city_ids = [];
                cities.forEach(function(cityrow) {
                   city_ids.push(cityrow.city_id);
                   
                   var theTrip = result.trips[cityrow.trip_id];
                   if (typeof theTrip.cities == 'undefined') {
                	   theTrip.cities={};
                   }
                   theTrip.cities[cityrow.city_id] = cityrow;
               });
              
               var chapter_query = "{\"city_id\":{ $in :["+city_ids+"]}}";
               gamedonia.data.search("saga_chapters",chapter_query,{
                   success:function(chapters) {
                       chapters.forEach(function(chapterrow) {
                           var theCity = result.trips[chapterrow.trip_id].cities[chapterrow.city_id];
                           if (typeof theCity.chapters == 'undefined') {
                        	   theCity.chapters={};
                           }
                    	   theCity.chapters[chapterrow.chapter_id] = chapterrow;
                       });
                       gamedonia.data.create("test_rep",toEntityData(result),{
                    	  success:function(e){
                              response.success(result); 
                    	  } 
                       });
                   },error:function(error) {
                       response.success(error.message);
                   }
               });
           },error:function(error) {
               response.success(error.message);
           }    
       });
   }, error:function(error) {
       response.success(error.message);
       
   }    
});