// Script: 'jobjjjj.js' , generated by Gamedonia
gamedonia.data.remove("apm", "56cc87e67d8488bc4d01d727", {

   success: function () {

       //printTest("REMOVE non_existent", false);
       response.success();
   },
   error: function (error) {

       //printTest("REMOVE non_existent", true);
       //testBulkOps();

       log.error(error.message);
       response.error(error.message);
   }

});